# Generated by Django 4.2.16 on 2024-10-25 13:11

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modificado_em', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('nome', models.CharField(max_length=64, unique=True, verbose_name='Modelo')),
                ('apresentacao', models.CharField(blank=True, max_length=512, null=True, verbose_name='Apresentação do modelo')),
                ('especificacoes', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Especificações do produto')),
                ('slug', models.SlugField(blank=True, max_length=64, null=True, verbose_name='Slug do modelo')),
                ('imagem_principal', models.URLField(max_length=256, verbose_name='Imagem principal do modelo')),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modificado_em', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('nome', models.CharField(max_length=64, unique=True, verbose_name='Produto')),
                ('slug', models.SlugField(blank=True, max_length=64, null=True, verbose_name='Slug do produto')),
                ('cod_sap_item', models.CharField(blank=True, max_length=8, null=True, verbose_name='Código SAP do Produto')),
                ('ean', models.CharField(blank=True, max_length=16, null=True)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='produto.modelo')),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
            },
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modificado_em', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('nome', models.CharField(max_length=64, unique=True, verbose_name='Subcategoria')),
                ('slug', models.SlugField(blank=True, max_length=64, null=True, verbose_name='Slug da subcategoria')),
            ],
            options={
                'verbose_name': 'Subcategoria',
                'verbose_name_plural': 'Subcategorias',
            },
        ),
        migrations.CreateModel(
            name='VideoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modificado_em', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('video_url', models.URLField(blank=True, max_length=256, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos_produto', to='produto.produto')),
            ],
            options={
                'verbose_name': 'Video do Produto',
                'verbose_name_plural': 'Videos do Produto',
                'ordering': ('pk',),
            },
        ),
        migrations.AddField(
            model_name='modelo',
            name='subcategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='produto.subcategoria'),
        ),
        migrations.CreateModel(
            name='ImagemProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modificado_em', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('foto', models.FileField(blank=True, max_length=300, null=True, upload_to='')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_produto', to='produto.produto')),
            ],
            options={
                'verbose_name': 'Produto foto',
                'verbose_name_plural': 'Produto fotos',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='ConteudoApoio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modificado_em', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('nome', models.CharField(max_length=64)),
                ('para_vet', models.BooleanField(default=False)),
                ('modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conteudos_apoio', to='produto.modelo')),
            ],
            options={
                'verbose_name': 'Conteúdo de apoio',
                'verbose_name_plural': 'Conteúdos de apoio',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ArquivoConteudoApoio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modificado_em', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('arquivo', models.FileField(max_length=256, upload_to='ConteudoApoio')),
                ('nome_arquivo', models.CharField(blank=True, max_length=64, null=True)),
                ('conteudo_apoio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos_conteudo_apoio', to='produto.conteudoapoio')),
            ],
            options={
                'verbose_name': 'Arquivo de conteúdo de apoio',
                'verbose_name_plural': 'Arquivos de conteúdos de apoio',
                'ordering': ('id',),
            },
        ),
    ]
