# Generated by Django 4.2.16 on 2024-10-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_alter_produto_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='apresentacao',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Apresentação do modelo'),
        ),
    ]
