# Generated by Django 4.2.16 on 2024-10-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_alter_modelo_apresentacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproduto',
            name='label',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
