# Generated by Django 4.2.16 on 2024-10-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_modelo_icone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelo',
            name='icone',
        ),
        migrations.AddField(
            model_name='conteudoapoio',
            name='icone',
            field=models.TextField(default='', verbose_name='Ícone HTML'),
        ),
    ]
