# Generated by Django 4.2.16 on 2024-10-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_remove_modelo_icone_conteudoapoio_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteudoapoio',
            name='icone',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Ícone HTML'),
        ),
    ]
